### ISSUE TITLE
BC 22 Update issue

### ISSUE THREAD

**Issue by mundanebcdev** [document-output/opplus-payment-advice#1]
Hello,
the procedure "GetPmtCountryReverse" is obsoleted in the new version of Continia OPplus (22.0.1.32781)
Please advise what this can be replaced with.
https://github.com/document-output/opplus-payment-advice/blob/8462f0c73419d828c21069f6b66022bc3f81000e/objects/1.0.1.0/BC19-DO-5.00-app/src/report/PTEDOPaymentAdvice.Report.al#L343

**Comment by sradloff** [comment]
Hi,
we have identified the issue and are preparing a new version.
The report, that causes your issue will be removed from the package as the OPplus standard report (which was the base of this duplicate) has been fixed in the meantime.
Please not that we will also have to change the finding of the report ID in the management codeunit as this has been changed with OPplus 21.

**Comment by celjetashehu24** [comment]
Hello @sradloff 

We are in BC Version: DE Business Central 24.5 (Platform 24.0.27388.0 + Application 24.5.23489.23968)
and we installed your app and import the template but when we try to send the advice we get the below message. your help is much appreciated. thank you
![Payment proposal error](https://github.com/user-attachments/assets/069185db-cb26-4f2f-8838-ea595bf37a54)
